# yaml-language-server: $schema=https://testingcf.jsdelivr.net/gh/StageDog/tavern_resource/src/工具经验/酒馆助手编写环境配置/tavern_helper_template/config.json
port: 6621
entries:
  - script: src/脚本示例/index.ts

  - script: src/界面示例/index.ts
    html: src/界面示例/index.html

  - script: src/脚本模板/index.ts

  - script: src/界面模板/index.ts
    html: src/界面模板/index.html
